// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *footermenu → linkgroup*
 */
export interface FootermenuDocumentDataLinkgroupItem {
	/**
	 * label field in *footermenu → linkgroup*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.linkgroup[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * link field in *footermenu → linkgroup*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.linkgroup[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *footermenu → socialmediagroup*
 */
export interface FootermenuDocumentDataSocialmediagroupItem {
	/**
	 * image field in *footermenu → socialmediagroup*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.socialmediagroup[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * imagelink field in *footermenu → socialmediagroup*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.socialmediagroup[].imagelink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	imagelink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for footermenu documents
 */
interface FootermenuDocumentData {
	/**
	 * logo field in *footermenu*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * description field in *footermenu*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * textrights field in *footermenu*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.textrights
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	textrights: prismic.RichTextField;
	
	/**
	 * linkgroup field in *footermenu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.linkgroup[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	linkgroup: prismic.GroupField<Simplify<FootermenuDocumentDataLinkgroupItem>>;
	
	/**
	 * socialmediagroup field in *footermenu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footermenu.socialmediagroup[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	socialmediagroup: prismic.GroupField<Simplify<FootermenuDocumentDataSocialmediagroupItem>>;
}

/**
 * footermenu document from Prismic
 *
 * - **API ID**: `footermenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FootermenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<FootermenuDocumentData>, "footermenu", Lang>;

type HomepageDocumentDataSlicesSlice = HeroSlice | IdeasSlice | CardListSlice | LogoListSlice | MetricsSlice | ServicesSlice | ProjectsSlice | ClientsSlice | StaffSlice | ContactSlice

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
	/**
	 * seotitle field in *homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.seotitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seotitle: prismic.KeyTextField;
	
	/**
	 * seodescription field in *homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.seodescription
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seodescription: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Item in *landingFooter → contactgroup*
 */
export interface LandingfooterDocumentDataContactgroupItem {
	/**
	 * icon field in *landingFooter → contactgroup*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.contactgroup[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;
	
	/**
	 * label field in *landingFooter → contactgroup*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.contactgroup[].label
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	label: prismic.RichTextField;
	
	/**
	 * url field in *landingFooter → contactgroup*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.contactgroup[].url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for landingFooter documents
 */
interface LandingfooterDocumentData {
	/**
	 * logo field in *landingFooter*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * description field in *landingFooter*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * copyright field in *landingFooter*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.copyright
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	copyright: prismic.RichTextField;
	
	/**
	 * contactgroup field in *landingFooter*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingfooter.contactgroup[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	contactgroup: prismic.GroupField<Simplify<LandingfooterDocumentDataContactgroupItem>>;
}

/**
 * landingFooter document from Prismic
 *
 * - **API ID**: `landingfooter`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingfooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<LandingfooterDocumentData>, "landingfooter", Lang>;

/**
 * Item in *landingNav → navlink*
 */
export interface LandingnavDocumentDataNavlinkItem {
	/**
	 * name field in *landingNav → navlink*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.navlink[].name
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	name: prismic.RichTextField;
	
	/**
	 * link field in *landingNav → navlink*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.navlink[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *landingNav → contanctbtn*
 */
export interface LandingnavDocumentDataContanctbtnItem {
	/**
	 * icon field in *landingNav → contanctbtn*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.contanctbtn[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;
	
	/**
	 * link field in *landingNav → contanctbtn*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.contanctbtn[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * label field in *landingNav → contanctbtn*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.contanctbtn[].label
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	label: prismic.RichTextField;
}

/**
 * Content for landingNav documents
 */
interface LandingnavDocumentData {
	/**
	 * logo field in *landingNav*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * logourl field in *landingNav*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.logourl
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	logourl: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * navlink field in *landingNav*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.navlink[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	navlink: prismic.GroupField<Simplify<LandingnavDocumentDataNavlinkItem>>;
	
	/**
	 * contanctbtn field in *landingNav*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingnav.contanctbtn[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	contanctbtn: prismic.GroupField<Simplify<LandingnavDocumentDataContanctbtnItem>>;
}

/**
 * landingNav document from Prismic
 *
 * - **API ID**: `landingnav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingnavDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<LandingnavDocumentData>, "landingnav", Lang>;

type LandingpageDocumentDataSlicesSlice = LandingStandoutSlice | LandingCountUpSlice | LandingFaqSlice | LandingCallbackSlice | LandingBannerSlice | LandingServicesSlice | LandingCustomerReviewSlice | LandingTimelineSlice | LandingEmpathySlice | LandingResponsibilitySlice

/**
 * Content for landingPage documents
 */
interface LandingpageDocumentData {
	/**
	 * seotitle field in *landingPage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingpage.seotitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seotitle: prismic.KeyTextField;
	
	/**
	 * seodescription field in *landingPage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingpage.seodescription
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seodescription: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *landingPage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landingpage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<LandingpageDocumentDataSlicesSlice>;
}

/**
 * landingPage document from Prismic
 *
 * - **API ID**: `landingpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingpageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<LandingpageDocumentData>, "landingpage", Lang>;

/**
 * Item in *menuTop → menuLinks*
 */
export interface MenutopDocumentDataMenulinksItem {
	/**
	 * label field in *menuTop → menuLinks*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.menulinks[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * link field in *menuTop → menuLinks*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.menulinks[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for menuTop documents
 */
interface MenutopDocumentData {
	/**
	 * logo field in *menuTop*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * title field in *menuTop*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * callToActionText field in *menuTop*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.calltoactiontext
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	calltoactiontext: prismic.RichTextField;
	
	/**
	 * callToActionURL field in *menuTop*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.calltoactionurl
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	calltoactionurl: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * menuLinks field in *menuTop*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menutop.menulinks[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	menulinks: prismic.GroupField<Simplify<MenutopDocumentDataMenulinksItem>>;
}

/**
 * menuTop document from Prismic
 *
 * - **API ID**: `menutop`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenutopDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<MenutopDocumentData>, "menutop", Lang>;

type PageDocumentDataSlicesSlice = HeroSlice | IdeasSlice | CardListSlice | LogoListSlice | MetricsSlice | ServicesSlice | ProjectsSlice | ClientsSlice | StaffSlice | ContactSlice

/**
 * Content for page documents
 */
interface PageDocumentData {
	/**
	 * seotitle field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.seotitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seotitle: prismic.KeyTextField;
	
	/**
	 * seodescription field in *page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.seodescription
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	seodescription: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = FootermenuDocument | HomepageDocument | LandingfooterDocument | LandingnavDocument | LandingpageDocument | MenutopDocument | PageDocument;

/**
 * Primary content in *CardList → Default → Primary*
 */
export interface CardListSliceDefaultPrimary {
	/**
	 * title field in *CardList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *CardList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *CardList → Items*
 */
export interface CardListSliceDefaultItem {
	/**
	 * cardTitle field in *CardList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.items[].cardTitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	cardTitle: prismic.RichTextField;
	
	/**
	 * cardDescription field in *CardList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.items[].cardDescription
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	cardDescription: prismic.RichTextField;
	
	/**
	 * cardImage field in *CardList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.items[].cardImage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cardImage: prismic.ImageField<never>;
}

/**
 * Default variation for CardList Slice
 *
 * - **API ID**: `default`
 * - **Description**: CardList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CardListSliceDefaultPrimary>, Simplify<CardListSliceDefaultItem>>;

/**
 * Slice variation for *CardList*
 */
type CardListSliceVariation = CardListSliceDefault

/**
 * CardList Shared Slice
 *
 * - **API ID**: `card_list`
 * - **Description**: CardList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardListSlice = prismic.SharedSlice<"card_list", CardListSliceVariation>;

/**
 * Primary content in *Comparative → Default → Primary*
 */
export interface ClientsSliceDefaultPrimary {
	/**
	 * title field in *Comparative → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *Comparative → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
}

/**
 * Primary content in *Comparative → Items*
 */
export interface ClientsSliceDefaultItem {
	/**
	 * title field in *Comparative → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * ico1 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	ico: prismic.ImageField<never>;
	
	/**
	 * description1 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description1
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description1: prismic.KeyTextField;
	
	/**
	 * ico2 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico2
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	ico2: prismic.ImageField<never>;
	
	/**
	 * description2 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description2
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description2: prismic.KeyTextField;
	
	/**
	 * ico3 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico3
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	ico3: prismic.ImageField<never>;
	
	/**
	 * description3 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description3
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description3: prismic.KeyTextField;
	
	/**
	 * ico4 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico4
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	ico4: prismic.ImageField<never>;
	
	/**
	 * description4 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description4
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description4: prismic.KeyTextField;
	
	/**
	 * ico5 field in *Comparative → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].ico5
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	ico5: prismic.ImageField<never>;
	
	/**
	 * description5 field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].description5
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description5: prismic.KeyTextField;
	
	/**
	 * buttontext field in *Comparative → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].buttontext
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	buttontext: prismic.KeyTextField;
	
	/**
	 * buttonlink field in *Comparative → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: clients.items[].buttonlink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	buttonlink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Comparative Slice
 *
 * - **API ID**: `default`
 * - **Description**: Clients
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ClientsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ClientsSliceDefaultPrimary>, Simplify<ClientsSliceDefaultItem>>;

/**
 * Slice variation for *Comparative*
 */
type ClientsSliceVariation = ClientsSliceDefault

/**
 * Comparative Shared Slice
 *
 * - **API ID**: `clients`
 * - **Description**: Clients
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ClientsSlice = prismic.SharedSlice<"clients", ClientsSliceVariation>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
	/**
	 * title field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * subtitle field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * name field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * email field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.email
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField;
	
	/**
	 * message field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.message
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	message: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ContactSliceDefaultPrimary>, never>;

/**
 * Primary content in *Contact → cotizarForm → Primary*
 */
export interface ContactSliceCotizarFormPrimary {
	/**
	 * subtitle field in *Contact → cotizarForm → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.cotizarForm.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * name field in *Contact → cotizarForm → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.cotizarForm.primary.name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * email field in *Contact → cotizarForm → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.cotizarForm.primary.email
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField;
}

/**
 * cotizarForm variation for Contact Slice
 *
 * - **API ID**: `cotizarForm`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceCotizarForm = prismic.SharedSliceVariation<"cotizarForm", Simplify<ContactSliceCotizarFormPrimary>, never>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault | ContactSliceCotizarForm

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<"contact", ContactSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * invertedLayout field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.default.primary.invertedlayout
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	invertedlayout: prismic.BooleanField;
	
	/**
	 * image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * description field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * buttonText field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	buttontext: prismic.KeyTextField;
	
	/**
	 * buttonLink field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.buttonlink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	buttonlink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * mobileImage field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.mobileimage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	mobileimage: prismic.ImageField<never>;
	
	/**
	 * title field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Primary content in *Hero → noButtonNoDescription → Primary*
 */
export interface HeroSliceNoButtonNoDescriptionPrimary {
	/**
	 * invertedLayout field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.noButtonNoDescription.primary.invertedlayout
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	invertedlayout: prismic.BooleanField;
	
	/**
	 * image field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButtonNoDescription.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * title field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButtonNoDescription.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * mobileImage field in *Hero → noButtonNoDescription → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButtonNoDescription.primary.mobileimage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	mobileimage: prismic.ImageField<never>;
}

/**
 * noButtonNoDescription variation for Hero Slice
 *
 * - **API ID**: `noButtonNoDescription`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceNoButtonNoDescription = prismic.SharedSliceVariation<"noButtonNoDescription", Simplify<HeroSliceNoButtonNoDescriptionPrimary>, never>;

/**
 * Primary content in *Hero → noButton → Primary*
 */
export interface HeroSliceNoButtonPrimary {
	/**
	 * invertedLayout field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.noButton.primary.invertedlayout
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	invertedlayout: prismic.BooleanField;
	
	/**
	 * image field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * title field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * mobileImage field in *Hero → noButton → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.noButton.primary.mobileimage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	mobileimage: prismic.ImageField<never>;
}

/**
 * noButton variation for Hero Slice
 *
 * - **API ID**: `noButton`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceNoButton = prismic.SharedSliceVariation<"noButton", Simplify<HeroSliceNoButtonPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceNoButtonNoDescription | HeroSliceNoButton

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Ideas → Default → Primary*
 */
export interface IdeasSliceDefaultPrimary {
	/**
	 * subtittle field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.subtittle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtittle: prismic.RichTextField;
	
	/**
	 * tittle field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.tittle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	tittle: prismic.RichTextField;
	
	/**
	 * buttonText field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	buttontext: prismic.KeyTextField;
	
	/**
	 * buttonLink field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.buttonlink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	buttonlink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * bgColorInitial field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.bgcolorInitial
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	bgcolorInitial: prismic.ColorField;
	
	/**
	 * bgColorEnd field in *Ideas → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.default.primary.bgcolorend
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	bgcolorend: prismic.ColorField;
}

/**
 * Default variation for Ideas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IdeasSliceDefault = prismic.SharedSliceVariation<"default", Simplify<IdeasSliceDefaultPrimary>, never>;

/**
 * Primary content in *Ideas → noButtonNobg → Primary*
 */
export interface IdeasSliceNoButtonNobgPrimary {
	/**
	 * subtittle field in *Ideas → noButtonNobg → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButtonNobg.primary.subtittle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtittle: prismic.RichTextField;
	
	/**
	 * tittle field in *Ideas → noButtonNobg → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButtonNobg.primary.tittle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	tittle: prismic.RichTextField;
}

/**
 * noButtonNobg variation for Ideas Slice
 *
 * - **API ID**: `noButtonNobg`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IdeasSliceNoButtonNobg = prismic.SharedSliceVariation<"noButtonNobg", Simplify<IdeasSliceNoButtonNobgPrimary>, never>;

/**
 * Primary content in *Ideas → noButton → Primary*
 */
export interface IdeasSliceNoButtonPrimary {
	/**
	 * subtittle field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.subtittle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtittle: prismic.RichTextField;
	
	/**
	 * tittle field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.tittle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	tittle: prismic.RichTextField;
	
	/**
	 * bgColorInitial field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.bgcolorInitial
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	bgcolorInitial: prismic.ColorField;
	
	/**
	 * bgColorEnd field in *Ideas → noButton → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ideas.noButton.primary.bgcolorend
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	bgcolorend: prismic.ColorField;
}

/**
 * noButton variation for Ideas Slice
 *
 * - **API ID**: `noButton`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IdeasSliceNoButton = prismic.SharedSliceVariation<"noButton", Simplify<IdeasSliceNoButtonPrimary>, never>;

/**
 * Slice variation for *Ideas*
 */
type IdeasSliceVariation = IdeasSliceDefault | IdeasSliceNoButtonNobg | IdeasSliceNoButton

/**
 * Ideas Shared Slice
 *
 * - **API ID**: `ideas`
 * - **Description**: Ideas
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IdeasSlice = prismic.SharedSlice<"ideas", IdeasSliceVariation>;

/**
 * Primary content in *LandingBanner → Default → Primary*
 */
export interface LandingBannerSliceDefaultPrimary {
	/**
	 * title field in *LandingBanner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_banner.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * subtitle field in *LandingBanner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_banner.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * formtitle field in *LandingBanner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_banner.default.primary.formtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	formtitle: prismic.RichTextField;
	
	/**
	 * formsubtitle field in *LandingBanner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_banner.default.primary.formsubtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	formsubtitle: prismic.RichTextField;
	
	/**
	 * bgimage field in *LandingBanner → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_banner.default.primary.bgimage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	bgimage: prismic.ImageField<never>;
	
	/**
	 * ctaText field in *LandingBanner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_banner.default.primary.ctatext
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	ctatext: prismic.RichTextField;
}

/**
 * Primary content in *LandingBanner → Items*
 */
export interface LandingBannerSliceDefaultItem {
	/**
	 * icon field in *LandingBanner → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_banner.items[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;
	
	/**
	 * keyword field in *LandingBanner → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_banner.items[].keyword
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	keyword: prismic.RichTextField;
}

/**
 * Default variation for LandingBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingBannerSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingBannerSliceDefaultPrimary>, Simplify<LandingBannerSliceDefaultItem>>;

/**
 * Slice variation for *LandingBanner*
 */
type LandingBannerSliceVariation = LandingBannerSliceDefault

/**
 * LandingBanner Shared Slice
 *
 * - **API ID**: `landing_banner`
 * - **Description**: LandingBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingBannerSlice = prismic.SharedSlice<"landing_banner", LandingBannerSliceVariation>;

/**
 * Primary content in *LandingCallbackForm → Default → Primary*
 */
export interface LandingCallbackSliceDefaultPrimary {
	/**
	 * Title field in *LandingCallbackForm → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_callback.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Description field in *LandingCallbackForm → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A nice description of your feature
	 * - **API ID Path**: landing_callback.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for LandingCallbackForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingCallback
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingCallbackSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingCallbackSliceDefaultPrimary>, never>;

/**
 * Slice variation for *LandingCallbackForm*
 */
type LandingCallbackSliceVariation = LandingCallbackSliceDefault

/**
 * LandingCallbackForm Shared Slice
 *
 * - **API ID**: `landing_callback`
 * - **Description**: LandingCallback
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingCallbackSlice = prismic.SharedSlice<"landing_callback", LandingCallbackSliceVariation>;

/**
 * Primary content in *LandingCountUp → Default → Primary*
 */
export interface LandingCountUpSliceDefaultPrimary {
	/**
	 * max field in *LandingCountUp → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_count_up.default.primary.max
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	max: prismic.NumberField;
	
	/**
	 * duration field in *LandingCountUp → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_count_up.default.primary.duration
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	duration: prismic.NumberField;
	
	/**
	 * text field in *LandingCountUp → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Clientes Satisfechos
	 * - **API ID Path**: landing_count_up.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for LandingCountUp Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingCountUp
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingCountUpSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingCountUpSliceDefaultPrimary>, never>;

/**
 * Slice variation for *LandingCountUp*
 */
type LandingCountUpSliceVariation = LandingCountUpSliceDefault

/**
 * LandingCountUp Shared Slice
 *
 * - **API ID**: `landing_count_up`
 * - **Description**: LandingCountUp
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingCountUpSlice = prismic.SharedSlice<"landing_count_up", LandingCountUpSliceVariation>;

/**
 * Primary content in *LandingCustomerReview → Default → Primary*
 */
export interface LandingCustomerReviewSliceDefaultPrimary {
	/**
	 * Title field in *LandingCustomerReview → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_customer_review.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *LandingCustomerReview → Items*
 */
export interface LandingCustomerReviewSliceDefaultItem {
	/**
	 * usericon field in *LandingCustomerReview → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_customer_review.items[].usericon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	usericon: prismic.ImageField<never>;
	
	/**
	 * username field in *LandingCustomerReview → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_customer_review.items[].username
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	username: prismic.RichTextField;
	
	/**
	 * userreview field in *LandingCustomerReview → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_customer_review.items[].userreview
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	userreview: prismic.RichTextField;
	
	/**
	 * stars field in *LandingCustomerReview → Items*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_customer_review.items[].stars
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	stars: prismic.NumberField;
}

/**
 * Default variation for LandingCustomerReview Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingCustomerReview
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingCustomerReviewSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingCustomerReviewSliceDefaultPrimary>, Simplify<LandingCustomerReviewSliceDefaultItem>>;

/**
 * Slice variation for *LandingCustomerReview*
 */
type LandingCustomerReviewSliceVariation = LandingCustomerReviewSliceDefault

/**
 * LandingCustomerReview Shared Slice
 *
 * - **API ID**: `landing_customer_review`
 * - **Description**: LandingCustomerReview
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingCustomerReviewSlice = prismic.SharedSlice<"landing_customer_review", LandingCustomerReviewSliceVariation>;

/**
 * Primary content in *LandingEmpathy → Default → Primary*
 */
export interface LandingEmpathySliceDefaultPrimary {
	/**
	 * Title field in *LandingEmpathy → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_empathy.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Description field in *LandingEmpathy → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A nice description of your feature
	 * - **API ID Path**: landing_empathy.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * footer field in *LandingEmpathy → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_empathy.default.primary.footer
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	footer: prismic.RichTextField;
	
	/**
	 * bgImg field in *LandingEmpathy → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_empathy.default.primary.bgimg
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	bgimg: prismic.ImageField<never>;
}

/**
 * Default variation for LandingEmpathy Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingEmpathy
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingEmpathySliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingEmpathySliceDefaultPrimary>, never>;

/**
 * Slice variation for *LandingEmpathy*
 */
type LandingEmpathySliceVariation = LandingEmpathySliceDefault

/**
 * LandingEmpathy Shared Slice
 *
 * - **API ID**: `landing_empathy`
 * - **Description**: LandingEmpathy
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingEmpathySlice = prismic.SharedSlice<"landing_empathy", LandingEmpathySliceVariation>;

/**
 * Primary content in *LandingFaq → Default → Primary*
 */
export interface LandingFaqSliceDefaultPrimary {
	/**
	 * Title field in *LandingFaq → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_faq.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *LandingFaq → Items*
 */
export interface LandingFaqSliceDefaultItem {
	/**
	 * question field in *LandingFaq → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_faq.items[].question
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	question: prismic.RichTextField;
	
	/**
	 * answer field in *LandingFaq → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_faq.items[].answer
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	answer: prismic.RichTextField;
}

/**
 * Default variation for LandingFaq Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingFaq
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingFaqSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingFaqSliceDefaultPrimary>, Simplify<LandingFaqSliceDefaultItem>>;

/**
 * Slice variation for *LandingFaq*
 */
type LandingFaqSliceVariation = LandingFaqSliceDefault

/**
 * LandingFaq Shared Slice
 *
 * - **API ID**: `landing_faq`
 * - **Description**: LandingFaq
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingFaqSlice = prismic.SharedSlice<"landing_faq", LandingFaqSliceVariation>;

/**
 * Primary content in *LandingResponsibility → Items*
 */
export interface LandingResponsibilitySliceDefaultItem {
	/**
	 * title field in *LandingResponsibility → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_responsibility.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *LandingResponsibility → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_responsibility.items[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * standout field in *LandingResponsibility → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_responsibility.items[].standout
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	standout: prismic.RichTextField;
}

/**
 * Default variation for LandingResponsibility Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingResponsibility
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingResponsibilitySliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<LandingResponsibilitySliceDefaultItem>>;

/**
 * Slice variation for *LandingResponsibility*
 */
type LandingResponsibilitySliceVariation = LandingResponsibilitySliceDefault

/**
 * LandingResponsibility Shared Slice
 *
 * - **API ID**: `landing_responsibility`
 * - **Description**: LandingResponsibility
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingResponsibilitySlice = prismic.SharedSlice<"landing_responsibility", LandingResponsibilitySliceVariation>;

/**
 * Primary content in *LandingServices → Default → Primary*
 */
export interface LandingServicesSliceDefaultPrimary {
	/**
	 * title field in *LandingServices → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *LandingServices → Items*
 */
export interface LandingServicesSliceDefaultItem {
	/**
	 * bgimage field in *LandingServices → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].bgimage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	bgimage: prismic.ImageField<never>;
	
	/**
	 * servicetitle field in *LandingServices → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].servicetitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	servicetitle: prismic.RichTextField;
	
	/**
	 * description field in *LandingServices → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * link field in *LandingServices → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for LandingServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingServices
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingServicesSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingServicesSliceDefaultPrimary>, Simplify<LandingServicesSliceDefaultItem>>;

/**
 * Primary content in *LandingServices → nohover → Primary*
 */
export interface LandingServicesSliceNohoverPrimary {
	/**
	 * title field in *LandingServices → nohover → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.nohover.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *LandingServices → Items*
 */
export interface LandingServicesSliceNohoverItem {
	/**
	 * bgimage field in *LandingServices → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].bgimage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	bgimage: prismic.ImageField<never>;
	
	/**
	 * servicetitle field in *LandingServices → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].servicetitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	servicetitle: prismic.RichTextField;
	
	/**
	 * description field in *LandingServices → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_services.items[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * nohover variation for LandingServices Slice
 *
 * - **API ID**: `nohover`
 * - **Description**: LandingServices
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingServicesSliceNohover = prismic.SharedSliceVariation<"nohover", Simplify<LandingServicesSliceNohoverPrimary>, Simplify<LandingServicesSliceNohoverItem>>;

/**
 * Slice variation for *LandingServices*
 */
type LandingServicesSliceVariation = LandingServicesSliceDefault | LandingServicesSliceNohover

/**
 * LandingServices Shared Slice
 *
 * - **API ID**: `landing_services`
 * - **Description**: LandingServices
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingServicesSlice = prismic.SharedSlice<"landing_services", LandingServicesSliceVariation>;

/**
 * Primary content in *LandingStandout → Default → Primary*
 */
export interface LandingStandoutSliceDefaultPrimary {
	/**
	 * title field in *LandingStandout → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: DESTACAMOS POR
	 * - **API ID Path**: landing_standout.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *LandingStandout → Items*
 */
export interface LandingStandoutSliceDefaultItem {
	/**
	 * icon field in *LandingStandout → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_standout.items[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;
	
	/**
	 * label field in *LandingStandout → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_standout.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	label: prismic.RichTextField;
}

/**
 * Default variation for LandingStandout Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingStandout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingStandoutSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingStandoutSliceDefaultPrimary>, Simplify<LandingStandoutSliceDefaultItem>>;

/**
 * Slice variation for *LandingStandout*
 */
type LandingStandoutSliceVariation = LandingStandoutSliceDefault

/**
 * LandingStandout Shared Slice
 *
 * - **API ID**: `landing_standout`
 * - **Description**: LandingStandout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingStandoutSlice = prismic.SharedSlice<"landing_standout", LandingStandoutSliceVariation>;

/**
 * Primary content in *LandingTimeline → Default → Primary*
 */
export interface LandingTimelineSliceDefaultPrimary {
	/**
	 * Title field in *LandingTimeline → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: landing_timeline.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *LandingTimeline → Items*
 */
export interface LandingTimelineSliceDefaultItem {
	/**
	 * step field in *LandingTimeline → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing_timeline.items[].step
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	step: prismic.RichTextField;
}

/**
 * Default variation for LandingTimeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: LandingTimeline
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingTimelineSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LandingTimelineSliceDefaultPrimary>, Simplify<LandingTimelineSliceDefaultItem>>;

/**
 * Slice variation for *LandingTimeline*
 */
type LandingTimelineSliceVariation = LandingTimelineSliceDefault

/**
 * LandingTimeline Shared Slice
 *
 * - **API ID**: `landing_timeline`
 * - **Description**: LandingTimeline
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingTimelineSlice = prismic.SharedSlice<"landing_timeline", LandingTimelineSliceVariation>;

/**
 * Primary content in *LogoList → Default → Primary*
 */
export interface LogoListSliceDefaultPrimary {
	/**
	 * title field in *LogoList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *LogoList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *LogoList → Items*
 */
export interface LogoListSliceDefaultItem {
	/**
	 * logoImage field in *LogoList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].logoImage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logoImage: prismic.ImageField<never>;
}

/**
 * Default variation for LogoList Slice
 *
 * - **API ID**: `default`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LogoListSliceDefaultPrimary>, Simplify<LogoListSliceDefaultItem>>;

/**
 * Primary content in *LogoList → Items*
 */
export interface LogoListSliceOnlyLogosBgItem {
	/**
	 * logoImage field in *LogoList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].logoImage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logoImage: prismic.ImageField<never>;
}

/**
 * onlyLogosBg variation for LogoList Slice
 *
 * - **API ID**: `onlyLogosBg`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoListSliceOnlyLogosBg = prismic.SharedSliceVariation<"onlyLogosBg", Record<string, never>, Simplify<LogoListSliceOnlyLogosBgItem>>;

/**
 * Primary content in *LogoList → buttonTitleDescription → Primary*
 */
export interface LogoListSliceButtonTitleDescriptionPrimary {
	/**
	 * title field in *LogoList → buttonTitleDescription → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.buttonTitleDescription.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *LogoList → Items*
 */
export interface LogoListSliceButtonTitleDescriptionItem {
	/**
	 * logoImage field in *LogoList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].logoImage
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logoImage: prismic.ImageField<never>;
	
	/**
	 * subtitle field in *LogoList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Titulo ...
	 * - **API ID Path**: logo_list.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * description field in *LogoList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Descripción ...
	 * - **API ID Path**: logo_list.items[].description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * buttonlink field in *LogoList → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].buttonlink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	buttonlink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * buttontext field in *LogoList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo_list.items[].buttontext
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	buttontext: prismic.KeyTextField;
}

/**
 * buttonTitleDescription variation for LogoList Slice
 *
 * - **API ID**: `buttonTitleDescription`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoListSliceButtonTitleDescription = prismic.SharedSliceVariation<"buttonTitleDescription", Simplify<LogoListSliceButtonTitleDescriptionPrimary>, Simplify<LogoListSliceButtonTitleDescriptionItem>>;

/**
 * Slice variation for *LogoList*
 */
type LogoListSliceVariation = LogoListSliceDefault | LogoListSliceOnlyLogosBg | LogoListSliceButtonTitleDescription

/**
 * LogoList Shared Slice
 *
 * - **API ID**: `logo_list`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoListSlice = prismic.SharedSlice<"logo_list", LogoListSliceVariation>;

/**
 * Primary content in *Metrics → Default → Primary*
 */
export interface MetricsSliceDefaultPrimary {
	/**
	 * title field in *Metrics → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *Metrics → Items*
 */
export interface MetricsSliceDefaultItem {
	/**
	 * contentText field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].contenttext
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contenttext: prismic.KeyTextField;
	
	/**
	 * subtitle field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for Metrics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Metrics
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MetricsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<MetricsSliceDefaultPrimary>, Simplify<MetricsSliceDefaultItem>>;

/**
 * Primary content in *Metrics → noBackground → Primary*
 */
export interface MetricsSliceNoBackgroundPrimary {
	/**
	 * title field in *Metrics → noBackground → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.noBackground.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *Metrics → Items*
 */
export interface MetricsSliceNoBackgroundItem {
	/**
	 * contentText field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].contenttext
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contenttext: prismic.KeyTextField;
	
	/**
	 * subtitle field in *Metrics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: metrics.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * noBackground variation for Metrics Slice
 *
 * - **API ID**: `noBackground`
 * - **Description**: Metrics
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MetricsSliceNoBackground = prismic.SharedSliceVariation<"noBackground", Simplify<MetricsSliceNoBackgroundPrimary>, Simplify<MetricsSliceNoBackgroundItem>>;

/**
 * Slice variation for *Metrics*
 */
type MetricsSliceVariation = MetricsSliceDefault | MetricsSliceNoBackground

/**
 * Metrics Shared Slice
 *
 * - **API ID**: `metrics`
 * - **Description**: Metrics
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MetricsSlice = prismic.SharedSlice<"metrics", MetricsSliceVariation>;

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
	/**
	 * imgSwapp field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.imgswapp
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	imgswapp: prismic.ImageField<never>;
	
	/**
	 * subtitle field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * description field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * title field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ProjectsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsSlice = prismic.SharedSlice<"projects", ProjectsSliceVariation>;

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
	/**
	 * title field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * image field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * buttontext field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.default.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	buttontext: prismic.KeyTextField;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
	/**
	 * imageList field in *Services → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].imagelist
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	imagelist: prismic.ImageField<never>;
	
	/**
	 * titleList field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].titlelist
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	titlelist: prismic.KeyTextField;
	
	/**
	 * descriptionList field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].descriptionlist
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	descriptionlist: prismic.KeyTextField;
	
	/**
	 * linkText field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].linktext
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	linktext: prismic.KeyTextField;
	
	/**
	 * link field in *Services → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ServicesSliceDefaultPrimary>, Simplify<ServicesSliceDefaultItem>>;

/**
 * Primary content in *Services → noIconsNoButtons → Primary*
 */
export interface ServicesSliceNoIconsNoButtonsPrimary {
	/**
	 * title field in *Services → noIconsNoButtons → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIconsNoButtons.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *Services → noIconsNoButtons → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIconsNoButtons.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * image field in *Services → noIconsNoButtons → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIconsNoButtons.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * noIconsNoButtons variation for Services Slice
 *
 * - **API ID**: `noIconsNoButtons`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceNoIconsNoButtons = prismic.SharedSliceVariation<"noIconsNoButtons", Simplify<ServicesSliceNoIconsNoButtonsPrimary>, never>;

/**
 * Primary content in *Services → noIcons → Primary*
 */
export interface ServicesSliceNoIconsPrimary {
	/**
	 * title field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * image field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * buttontext field in *Services → noIcons → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.noIcons.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	buttontext: prismic.KeyTextField;
}

/**
 * noIcons variation for Services Slice
 *
 * - **API ID**: `noIcons`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceNoIcons = prismic.SharedSliceVariation<"noIcons", Simplify<ServicesSliceNoIconsPrimary>, never>;

/**
 * Primary content in *Services → imageText → Primary*
 */
export interface ServicesSliceImageTextPrimary {
	/**
	 * title field in *Services → imageText → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.imageText.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * image field in *Services → imageText → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.imageText.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * imageText variation for Services Slice
 *
 * - **API ID**: `imageText`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceImageText = prismic.SharedSliceVariation<"imageText", Simplify<ServicesSliceImageTextPrimary>, never>;

/**
 * Primary content in *Services → default-no-ver-mas → Primary*
 */
export interface ServicesSliceDefaultNoVerMasPrimary {
	/**
	 * title field in *Services → default-no-ver-mas → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.defaultNoVerMas.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * description field in *Services → default-no-ver-mas → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.defaultNoVerMas.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * image field in *Services → default-no-ver-mas → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.defaultNoVerMas.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * buttontext field in *Services → default-no-ver-mas → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.defaultNoVerMas.primary.buttontext
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	buttontext: prismic.KeyTextField;
	
	/**
	 * buttonLink field in *Services → default-no-ver-mas → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.defaultNoVerMas.primary.buttonlink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	buttonlink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultNoVerMasItem {
	/**
	 * imageList field in *Services → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].imagelist
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	imagelist: prismic.ImageField<never>;
	
	/**
	 * titleList field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].titlelist
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	titlelist: prismic.KeyTextField;
	
	/**
	 * descriptionList field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].descriptionlist
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	descriptionlist: prismic.KeyTextField;
}

/**
 * default-no-ver-mas variation for Services Slice
 *
 * - **API ID**: `defaultNoVerMas`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefaultNoVerMas = prismic.SharedSliceVariation<"defaultNoVerMas", Simplify<ServicesSliceDefaultNoVerMasPrimary>, Simplify<ServicesSliceDefaultNoVerMasItem>>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault | ServicesSliceNoIconsNoButtons | ServicesSliceNoIcons | ServicesSliceImageText | ServicesSliceDefaultNoVerMas

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<"services", ServicesSliceVariation>;

/**
 * Primary content in *Staff → Default → Primary*
 */
export interface StaffSliceDefaultPrimary {
	/**
	 * title field in *Staff → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
}

/**
 * Primary content in *Staff → Items*
 */
export interface StaffSliceDefaultItem {
	/**
	 * image field in *Staff → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * nametitle field in *Staff → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].nametitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	nametitle: prismic.KeyTextField;
	
	/**
	 * positiontitle field in *Staff → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].positiontitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	positiontitle: prismic.KeyTextField;
	
	/**
	 * linkedinlogo field in *Staff → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].linkedinlogo
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	linkedinlogo: prismic.ImageField<never>;
	
	/**
	 * profileurl field in *Staff → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: staff.items[].profileurl
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	profileurl: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Staff Slice
 *
 * - **API ID**: `default`
 * - **Description**: Staff
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StaffSliceDefault = prismic.SharedSliceVariation<"default", Simplify<StaffSliceDefaultPrimary>, Simplify<StaffSliceDefaultItem>>;

/**
 * Slice variation for *Staff*
 */
type StaffSliceVariation = StaffSliceDefault

/**
 * Staff Shared Slice
 *
 * - **API ID**: `staff`
 * - **Description**: Staff
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StaffSlice = prismic.SharedSlice<"staff", StaffSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismicClient.ClientConfig): prismicClient.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismicClient.WriteClientConfig): prismicClient.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismicClient.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			FootermenuDocument,
			FootermenuDocumentData,
			FootermenuDocumentDataLinkgroupItem,
			FootermenuDocumentDataSocialmediagroupItem,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			LandingfooterDocument,
			LandingfooterDocumentData,
			LandingfooterDocumentDataContactgroupItem,
			LandingnavDocument,
			LandingnavDocumentData,
			LandingnavDocumentDataNavlinkItem,
			LandingnavDocumentDataContanctbtnItem,
			LandingpageDocument,
			LandingpageDocumentData,
			LandingpageDocumentDataSlicesSlice,
			MenutopDocument,
			MenutopDocumentData,
			MenutopDocumentDataMenulinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			CardListSlice,
			CardListSliceDefaultPrimary,
			CardListSliceDefaultItem,
			CardListSliceVariation,
			CardListSliceDefault,
			ClientsSlice,
			ClientsSliceDefaultPrimary,
			ClientsSliceDefaultItem,
			ClientsSliceVariation,
			ClientsSliceDefault,
			ContactSlice,
			ContactSliceDefaultPrimary,
			ContactSliceCotizarFormPrimary,
			ContactSliceVariation,
			ContactSliceDefault,
			ContactSliceCotizarForm,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceNoButtonNoDescriptionPrimary,
			HeroSliceNoButtonPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroSliceNoButtonNoDescription,
			HeroSliceNoButton,
			IdeasSlice,
			IdeasSliceDefaultPrimary,
			IdeasSliceNoButtonNobgPrimary,
			IdeasSliceNoButtonPrimary,
			IdeasSliceVariation,
			IdeasSliceDefault,
			IdeasSliceNoButtonNobg,
			IdeasSliceNoButton,
			LandingBannerSlice,
			LandingBannerSliceDefaultPrimary,
			LandingBannerSliceDefaultItem,
			LandingBannerSliceVariation,
			LandingBannerSliceDefault,
			LandingCallbackSlice,
			LandingCallbackSliceDefaultPrimary,
			LandingCallbackSliceVariation,
			LandingCallbackSliceDefault,
			LandingCountUpSlice,
			LandingCountUpSliceDefaultPrimary,
			LandingCountUpSliceVariation,
			LandingCountUpSliceDefault,
			LandingCustomerReviewSlice,
			LandingCustomerReviewSliceDefaultPrimary,
			LandingCustomerReviewSliceDefaultItem,
			LandingCustomerReviewSliceVariation,
			LandingCustomerReviewSliceDefault,
			LandingEmpathySlice,
			LandingEmpathySliceDefaultPrimary,
			LandingEmpathySliceVariation,
			LandingEmpathySliceDefault,
			LandingFaqSlice,
			LandingFaqSliceDefaultPrimary,
			LandingFaqSliceDefaultItem,
			LandingFaqSliceVariation,
			LandingFaqSliceDefault,
			LandingResponsibilitySlice,
			LandingResponsibilitySliceDefaultItem,
			LandingResponsibilitySliceVariation,
			LandingResponsibilitySliceDefault,
			LandingServicesSlice,
			LandingServicesSliceDefaultPrimary,
			LandingServicesSliceDefaultItem,
			LandingServicesSliceNohoverPrimary,
			LandingServicesSliceNohoverItem,
			LandingServicesSliceVariation,
			LandingServicesSliceDefault,
			LandingServicesSliceNohover,
			LandingStandoutSlice,
			LandingStandoutSliceDefaultPrimary,
			LandingStandoutSliceDefaultItem,
			LandingStandoutSliceVariation,
			LandingStandoutSliceDefault,
			LandingTimelineSlice,
			LandingTimelineSliceDefaultPrimary,
			LandingTimelineSliceDefaultItem,
			LandingTimelineSliceVariation,
			LandingTimelineSliceDefault,
			LogoListSlice,
			LogoListSliceDefaultPrimary,
			LogoListSliceDefaultItem,
			LogoListSliceOnlyLogosBgItem,
			LogoListSliceButtonTitleDescriptionPrimary,
			LogoListSliceButtonTitleDescriptionItem,
			LogoListSliceVariation,
			LogoListSliceDefault,
			LogoListSliceOnlyLogosBg,
			LogoListSliceButtonTitleDescription,
			MetricsSlice,
			MetricsSliceDefaultPrimary,
			MetricsSliceDefaultItem,
			MetricsSliceNoBackgroundPrimary,
			MetricsSliceNoBackgroundItem,
			MetricsSliceVariation,
			MetricsSliceDefault,
			MetricsSliceNoBackground,
			ProjectsSlice,
			ProjectsSliceDefaultPrimary,
			ProjectsSliceVariation,
			ProjectsSliceDefault,
			ServicesSlice,
			ServicesSliceDefaultPrimary,
			ServicesSliceDefaultItem,
			ServicesSliceNoIconsNoButtonsPrimary,
			ServicesSliceNoIconsPrimary,
			ServicesSliceImageTextPrimary,
			ServicesSliceDefaultNoVerMasPrimary,
			ServicesSliceDefaultNoVerMasItem,
			ServicesSliceVariation,
			ServicesSliceDefault,
			ServicesSliceNoIconsNoButtons,
			ServicesSliceNoIcons,
			ServicesSliceImageText,
			ServicesSliceDefaultNoVerMas,
			StaffSlice,
			StaffSliceDefaultPrimary,
			StaffSliceDefaultItem,
			StaffSliceVariation,
			StaffSliceDefault
		}
	}
}