// Code generated by Slice Machine. DO NOT EDIT.

import CardList from './CardList';
import Comparative from './Comparative';
import Contact from './Contact';
import Hero from './Hero';
import Ideas from './Ideas';
import LandingBanner from './LandingBanner';
import LandingCallbackForm from './LandingCallbackForm';
import LandingCountUp from './LandingCountUp';
import LandingCustomerReview from './LandingCustomerReview';
import LandingEmpathy from './LandingEmpathy';
import LandingFaq from './LandingFaq';
import LandingServices from './LandingServices';
import LandingStandout from './LandingStandout';
import LandingTimeline from './LandingTimeline';
import LogoList from './LogoList';
import Metrics from './Metrics';
import Projects from './Projects';
import Services from './Services';
import Staff from './Staff';

export {
	CardList,
	Comparative,
	Contact,
	Hero,
	Ideas,
	LandingBanner,
	LandingCallbackForm,
	LandingCountUp,
	LandingCustomerReview,
	LandingEmpathy,
	LandingFaq,
	LandingServices,
	LandingStandout,
	LandingTimeline,
	LogoList,
	Metrics,
	Projects,
	Services,
	Staff,
};

export const components = {
	card_list: CardList,
	clients: Comparative,
	contact: Contact,
	hero: Hero,
	ideas: Ideas,
	landing_banner: LandingBanner,
	landing_callback: LandingCallbackForm,
	landing_count_up: LandingCountUp,
	landing_customer_review: LandingCustomerReview,
	landing_empathy: LandingEmpathy,
	landing_faq: LandingFaq,
	landing_services: LandingServices,
	landing_standout: LandingStandout,
	landing_timeline: LandingTimeline,
	logo_list: LogoList,
	metrics: Metrics,
	projects: Projects,
	services: Services,
	staff: Staff,
};
